[package]
name = "solana-collider"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
solana-program = "~1.18.26"
thiserror = "1.0"
spl-token-2022 = { version = "=1.0.0", features = ["no-entrypoint"] }
borsh = "0.10"
anchor-lang = "0.28.0"
anchor-spl = "0.28.0"

[dev-dependencies]
solana-program-test = "~1.18.26"
solana-sdk = "~1.18.26"
tokio = { version = "1.28", features = ["full"] }